Homework 1 - [Your name here]
========================================================

### Task 1 - Implementation

<!--
Use this section to implement the fizzbuzz function.

This should include a short write up describing your approach
to implementing the function. Note that both code formating / style
and your writeup matter for your overall grade.
-->

```{r}
fizzbuzz = function(v) {

  for (i in 1:length(v)) {
    if (is.numeric(v[i]) == FALSE) {
      print("Input is not numerric")
    }else if (is.infinite(v[i]) == TRUE | v[i] %% 1 != 0) {
      print("Input is not integer")
    }else if(v[i] %% 3 == 0 & v[i] %% 5 == 0){
      print("FizzBuzz")
    }else if (v[i] %% 5 == 0) {
      print("Buzz")
    }else if (v[i] %% 3 == 0) {
      print("Fizz")
    }else print(v[i]) 
  }
}
```

### Task 2 - Validation & Testing

#### Good Inputs

```{r}
fizzbuzz(1)
fizzbuzz(3)
fizzbuzz(5)
fizzbuzz(15)

fizzbuzz(9:15)
fizzbuzz(15:9)
```


#### Bad Inputs

```{r error=TRUE}
fizzbuzz(-1)
fizzbuzz(-3)
fizzbuzz(-5)

fizzbuzz(Inf)
fizzbuzz(-Inf)

fizzbuzz("A")
fizzbuzz(1.5)
fizzbuzz(1i)
fizzbuzz(4i)
```


